front:
  source: "/dev/v4l/by-path/platform-xhci-hcd.1-usb-0:1:1.0-video-index0"

  # Video
  frame_rate: 60
  width: 1920
  height: 1080
  format: "MJPEG"

  # Network
  host: "192.168.2.1"
  port: 5000

  # Configuration
  profile: "PHOTOGRAMMETRY"
  mode: "default"

